stages:
  - stage: build
    displayName: Build
    jobs:
      # Lint
      - template: .ci/rust/jobs/lint.yml

      # Build and test
      - job: build
        displayName: Build
        strategy:
          matrix:
            windows-stable:
              imageName: 'vs2017-win2016'
              rustupToolchain: stable
              exportTests: 'false'
              displayName: Windows
            mac-stable:
              imageName: 'macos-10.13'
              rustupToolchain: stable
              exportTests: 'false'
              displayName: OSX
            linux-stable:
              imageName: 'ubuntu-16.04'
              rustupToolchain: stable
              exportTests: 'false'
              displayName: Linux
            linux-beta:
              imageName: 'ubuntu-16.04'
              rustupToolchain: beta
              exportTests: 'false'
              displayName: Linux (Beta)
            linux-nightly:
              imageName: 'ubuntu-16.04'
              rustupToolchain: nightly
              exportTests: 'true'
              displayName: Linux (Nightly)

        pool:
          vmImage: $(imageName)

        steps:
          - template: .ci/rust/steps/test.yml
            parameters:
              rustupToolchain: $(rustupToolchain)
              exportTests: $(exportTests)
