stages:
  - stage: build
    displayName: Build
    jobs:
      # Lint
      - template: .ci/rust/jobs/lint.yml

      # Build and test
      - template: .ci/rust/jobs/build.yml
        parameters:
          os: windows

      - template: .ci/rust/jobs/build.yml
        parameters:
          os: osx

      - template: .ci/rust/jobs/build.yml

      - template: .ci/rust/jobs/build.yml
        parameters:
          toolchain: beta

      - template: .ci/rust/jobs/build.yml
        parameters:
          toolchain: nightly
      # - job: build
      #   displayName: Build
      #   strategy:
      #     matrix:
      #       windows-stable:
      #         imageName: 'vs2017-win2016'
      #         rustupToolchain: stable
      #         exportTests: 'false'
      #         windows: 'true'
      #         displayName: Windows
      #       mac-stable:
      #         imageName: 'macos-10.13'
      #         rustupToolchain: stable
      #         exportTests: 'false'
      #         windows: 'false'
      #         displayName: OSX
      #       linux-stable:
      #         imageName: 'ubuntu-16.04'
      #         rustupToolchain: stable
      #         exportTests: 'false'
      #         windows: 'false'
      #         displayName: Linux
      #       linux-beta:
      #         imageName: 'ubuntu-16.04'
      #         rustupToolchain: beta
      #         exportTests: 'false'
      #         windows: 'false'
      #         displayName: Linux (Beta)
      #       linux-nightly:
      #         imageName: 'ubuntu-16.04'
      #         rustupToolchain: nightly
      #         exportTests: 'true'
      #         windows: 'false'
      #         displayName: Linux (Nightly)

      #   pool:
      #     vmImage: $(imageName)

      #   steps:
      #     - template: .ci/rust/steps/test.yml
      #       parameters:
      #         rustupToolchain: '$(rustupToolchain)'
      #         exportTests: '$(exportTests)'
      #         windows: '$(windows)'
