stages:
  - stage: build
    displayName: Build
    jobs:
      # Lint
      - template: .ci/rust/jobs/lint.yml

      # Build and test
      - template: .ci/rust/jobs/build.yml
        parameters:
          os: windows

      - template: .ci/rust/jobs/build.yml
        parameters:
          os: osx

      - template: .ci/rust/jobs/build.yml

      - template: .ci/rust/jobs/build.yml
        parameters:
          toolchain: beta

      - template: .ci/rust/jobs/build.yml
        parameters:
          toolchain: nightly
